name: Node CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn run test
      - name: lint
        run: yarn run lint
      - name: publish dry-run
        run: npm publish --dry-run
